services:
  # Concourse services
  concourse-db:
    image: postgres:14
    platform: linux/amd64
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
    volumes:
      - concourse-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U concourse_user -d concourse"]
      interval: 5s
      timeout: 5s
      retries: 5

  concourse-web:
    image: concourse/concourse:7.9
    platform: linux/amd64
    command: web
    depends_on:
      concourse-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      # For simplicity, disable auth for local development
      CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 5s
      retries: 10

  concourse-worker:
    image: concourse/concourse:7.9
    platform: linux/amd64
    command: worker
    privileged: true
    depends_on:
      concourse-web:
        condition: service_healthy
    volumes:
      - concourse-worker-data:/worker-state
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8

  # Test runner container
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      concourse-web:
        condition: service_healthy
    volumes:
      - .:/app
      - ./test-results:/test-results
      - ./test-ssh:/root/.ssh
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CONCOURSE_URL=http://concourse-web:8080
      - GIT_WORKSPACE=/root/git
      - PIPELINE_HELPERS_LOG_TO_FILE=1
      - SSH_PRIVATE_KEY_PATH=/root/.ssh/id_rsa
      - REPOS_OWNER=malston
      - FOUNDATION_NAME=test-foundation
    command: /app/scripts/run-tests.sh

volumes:
  concourse-db-data:
  concourse-worker-data: